name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**/*.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**/*.just"

jobs:
  validate-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Just
        shell: bash
        run: bash .github/workflows/shared/install-just.sh
        
      - name: Check Just Syntax
        shell: bash
        run: |
          just check
