name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**/*.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**/*.just"

jobs:
  validate-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Just
        shell: bash
        run: bash .github/workflows/shared/install-just.sh
        
      - name: Check Just Syntax
        shell: bash
        run: |
          just check
