name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**/*.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**/*.just"

jobs:
  validate-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Just
        shell: bash
        run: bash .github/workflows/shared/install-just.sh
        
      - name: Check Just Syntax
        shell: bash
        run: |
          just check
